version: "3.9"
services:
    book-database:
        build: ./book-database
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
        # ports:
            # Not needed unless testing
            # - "3306:3306"

    book-service:
        build: ./book-service
        environment:
            BOOK_DATABASE: book-database
            MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
            # Not needed unless testing
            - "82:8080"

    library-service:
        build: ./library-service
        environment:
            BOOK_SERVICE_URL: "http://book-service:8080/"
        ports:
            # Not needed unless testing
            - "81:8080"

    library-app:
        build: ./library-app
        ports:
            - "80:80"
